# Generated by Django 5.1.2 on 2024-10-26 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_customuser_managers_customuser_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDish',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('map_link', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_favorite', models.BooleanField(default=True)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
