# Generated by Django 5.1.2 on 2024-10-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritefood',
            name='user',
        ),
    ]
