# Generated by Django 5.1.2 on 2024-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritedish',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
