# Generated by Django 5.1.2 on 2024-10-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0004_remove_favoritedish_food_remove_favoritedish_tried_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritedish',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyFavoriteDishes.food'),
        ),
    ]
