# Generated by Django 5.1.2 on 2024-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0007_alter_favoritedish_id_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='flavor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
