# Generated by Django 5.1.2 on 2024-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0009_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedish',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoritedish',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favoritedish',
            name='flavor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritedish',
            name='map_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoritedish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritedish',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='flavor',
            field=models.CharField(max_length=100),
        ),
    ]
