# Generated by Django 5.1.2 on 2024-10-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFavoriteDishes', '0011_favoritedish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritedish',
            name='is_favorite',
            field=models.BooleanField(default=True),
        ),
    ]
