# Generated by Django 5.1.2 on 2024-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=155)),
                ('rasa', models.CharField(max_length=6)),
                ('jenis', models.CharField(max_length=7)),
                ('nama_restoran', models.TextField()),
                ('harga', models.IntegerField()),
                ('link_gmaps', models.URLField()),
                ('alamat', models.TextField()),
            ],
        ),
    ]
