# Generated by Django 5.1.2 on 2024-10-26 09:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module4", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newdish",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
