# Generated by Django 5.1.2 on 2024-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdish',
            name='vendor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
