# Generated by Django 5.1.2 on 2024-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module4', '0002_alter_newdish_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdish',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
