# Generated by Django 5.1.2 on 2024-10-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module4', '0003_alter_newdish_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdish',
            old_name='alamat',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='newdish',
            old_name='jenis',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='newdish',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='newdish',
            old_name='harga',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='newdish',
            old_name='nama_restoran',
            new_name='restaurant_name',
        ),
        migrations.RenameField(
            model_name='newdish',
            old_name='rasa',
            new_name='taste',
        ),
    ]
