# Generated by Django 5.1.2 on 2024-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module4', '0006_alter_newdish_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdish',
            name='link_gmaps',
        ),
        migrations.RemoveField(
            model_name='newdish',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='newdish',
            name='taste',
        ),
        migrations.AddField(
            model_name='newdish',
            name='flavor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newdish',
            name='map_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newdish',
            name='vendor_name',
            field=models.CharField(default='Unknown Vendor', max_length=100),
        ),
        migrations.AlterField(
            model_name='newdish',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newdish',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newdish',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
