# Generated by Django 5.1.2 on 2024-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.CharField(max_length=255),
        ),
    ]
