# Generated by Django 5.1.2 on 2024-10-26 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_food_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
    ]
