# Generated by Django 4.2.6 on 2024-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_food_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRating',
            new_name='FoodRating',
        ),
    ]
