# Generated by Django 5.1.2 on 2024-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_customuser_managers_customuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.CharField(
                blank=True, default="Indonesia", max_length=255, null=True
            ),
        ),
    ]
