# Generated by Django 5.1.2 on 2024-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_food_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="description",
        ),
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.TextField(
                blank=True, default="No description yet.", null=True
            ),
        ),
    ]
