# Generated by Django 4.2.6 on 2024-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_productrating_foodrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='FoodRating',
        ),
    ]
